# This file stores configurations for your Shopify app.
client_id = "28895ec88647c70351b5d08ac9e98bae"
name = "ambitionkids-discountapp"
application_url = "https://shopify.dev/apps/default-react-router-app"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_discounts,write_discounts"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = ["https://shopify.dev/apps/default-react-router-app/auth/callback"]

[build]
automatically_update_urls_on_dev = true
