# This file stores configurations for your Shopify app.
client_id = "91ed9a3a235f1f86804b4faf93c4a9dc"
name = "ambitionkids-discountapp"
application_url = "https://ambitionkids-discount-function.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_discounts,write_discounts"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = ["https://ambitionkids-discount-function.onrender.com/auth/callback"]

[build]
automatically_update_urls_on_dev = false

