api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "ambitionkids-dicountapp"
type = "function"
uid = "02ae5595-f4d7-b92b-6fe7-1e8b499049617dd413f4"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
